name: Build My App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }

      - name: Prep Project
        run: |
          # السطر ده هيدور على أي ملف zip ويفكه مهما كان اسمه
          unzip *.zip || echo "مالقتش ملفات zip يا محمد!"
          
          # بنجبره يشوف الملفات اللي اتفكت
          ls -la
          
          # تثبيت المكتبات
          npm install --legacy-peer-deps
          npm run build
          npx cap add android
          npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mohamed-APK
          path: android/app/build/outputs/apk/debug/*.apk
          
